package org.thinktanktutoringservice.people;
import org.thinktanktutoringservice.hardware.*;

import org.thinktanktutoringservice.software.*;

public class InitializeDatabase {
public static void main (String[] args) {
	boolean b = false;
	Admin database = new Admin();
	MasterSchedule master = database.getMasterschedule();
	Department d1 = new Department("ECE");
	Department d2 = new Department("MATH");
	Department d3 = new Department("CS");
	Student s1 = new Student(1, "Senior",d1 , "Abdalrahman Albthali", "albthali@email.arizona.edu", "1995-3-9" , "albthali" , "password");
	Student s2 = new Student(2, "Senior",d1 , "Mohammed Alkhars", "Alkhars@email.arizona.edu", "1993-4-12" , "alkhars" , "password");
	Student s3 = new Student(3, "Junior",d2 , "Suzanne McCalla", "McCalla@email.arizona.edu", "1994-6-2" , "McCalla" , "password");
	Student s4 = new Student(4, "Junior",d2 , "Thomas Sewell", "Sewell@email.arizona.edu", "1995-7-13" , "Sewell" , "password");
	Student s5 = new Student(5, "Sophomore",d3 , "Dennis Paradiso", "Dennis@email.arizona.edu", "1996-1-10" , "Dennis" , "password");
	Student s6 = new Student(5, "Sophomore",d3 , "Karen Ponce", "Karen@email.arizona.edu", "1993-10-15" , "Karen" , "password");
	Course c1 = new Course("Introduction to Programming",  175, d1);
	Course c2 = new Course("Introduction to circuits",  220, d1);
	Course c3 = new Course("Object Oriented Programming",  275, d1);
	Course c4 = new Course("Vector Calculus",  223, d2);
	Course c5 = new Course("Calculus 2",  129, d2);
	Course c6 = new Course("Differential Equations",  254, d2);
	Course c7 = new Course("Computer Programming I",  110, d3);
	Course c8 = new Course("Software Development",  210, d3);
	Course c9 = new Course("Web Programming",  337, d3);
	Room r1 = new Room("Gymnasium", 233);
	Room r2 = new Room("Gymnasium", 254);
	Room r3 = new Room("Gymnasium", 212);
	Room r4 = new Room("Gymnasium", 323);
	Room r5 = new Room("Gymnasium", 351);
	Room r6 = new Room("Gymnasium", 342);
	Room r7 = new Room("Gymnasium", 361);
	Room r8 = new Room("Gymnasium", 266);
	Room r9 = new Room("Gymnasium", 258);
	Tutor t1 = new Tutor(101, 15 ,"Mary Coleman", "Mary@email.arizona.edu", "1989-8-23" , "Mary" , "password");
	Tutor t2 = new Tutor(102, 15 ,"Thomas Perez", "Perez@email.arizona.edu", "1988-12-25" , "Perez" , "password");
	Tutor t3 = new Tutor(103, 15 ,"Alan Brannon", "Brannon@email.arizona.edu", "1990-9-30" , "Brannon" , "password");
	Tutor t4 = new Tutor(104, 15 ,"Anthony Crawford", "Crawford@email.arizona.edu", "1991-5-29" , "Crawford" , "password");
	Tutor t5 = new Tutor(105, 15 ,"Pamela Chee", "Chee@email.arizona.edu", "1992-6-29" , "Chee" , "password");
	Tutor t6 = new Tutor(106, 15 ,"Tiffany Chavez", "Tiffany@email.arizona.edu", "1991-10-2" , "Tiffany" , "password");
	s1.addCourse(c1);
	s1.addCourse(c2);
	s1.addCourse(c3);
	s1.addCourse(c9);
	s2.addCourse(c1);
	s2.addCourse(c2);
	s2.addCourse(c3);
	s2.addCourse(c4);
	s3.addCourse(c6);
	s3.addCourse(c5);
	s3.addCourse(c7);
	s4.addCourse(c5);
	s4.addCourse(c6);
	s5.addCourse(c4);
	s5.addCourse(c8);
	s5.addCourse(c9);
	s6.addCourse(c9);
	s6.addCourse(c8);
	s6.addCourse(c5);
	s6.addCourse(c6);
	b = t1.addCourse(c1);
	b = t1.addCourse(c2);
	b = t1.addCourse(c4);
	b = t1.addCourse(c5);
	b = t2.addCourse(c7);
	b = t2.addCourse(c8);
	b = t2.addCourse(c9);
	b = t2.addCourse(c4);
	b = t2.addCourse(c5);
	b = t3.addCourse(c4);
	b = t3.addCourse(c5);
	b = t3.addCourse(c6);
	b = t4.addCourse(c1);
	b = t4.addCourse(c3);
	b = t4.addCourse(c7);
	b = t4.addCourse(c8);
	b = t4.addCourse(c9);
	b = t5.addCourse(c1);
	b = t5.addCourse(c2);
	b = t5.addCourse(c3);
	b = t5.addCourse(c4);
	b = t5.addCourse(c5);
	b = t6.addCourse(c4);
	b = t6.addCourse(c3);
	b = t6.addCourse(c2);
	b = t6.addCourse(c1);
	TutorSlot ts1 = new TutorSlot("2017 5 12 Tuesday 4:00 6:00", r1 , t1);
	TutorSlot ts2 = new TutorSlot("2017 5 12 Tuesday 2:00 4:00", r1 , t2);
	TutorSlot ts3 = new TutorSlot("2017 5 12 Tuesday 12:00 2:00", r1 , t1);
	TutorSlot ts4 = new TutorSlot("2017 4 12 Monday 12:00 2:00", r2 , t3);
	TutorSlot ts5 = new TutorSlot("2017 4 12 Monday 2:00 4:00", r2 , t3);
	TutorSlot ts6 = new TutorSlot("2017 4 12 Monday 12:00 2:00", r3 , t4);
	TutorSlot ts7 = new TutorSlot("2017 4 12 Monday 2:00 4:00", r3 , t4);
	TutorSlot ts8 = new TutorSlot("2017 6 12 Wednesday 2:00 4:00", r4 , t5);
	TutorSlot ts9 = new TutorSlot("2017 6 12 Wednesday 4:00 6:00", r4 , t5);
	TutorSlot ts10 = new TutorSlot("2017 6 12 Wednesday 12:00 2:00", r5 , t6);
	TutorSlot ts11 = new TutorSlot("2017 6 12 Wednesday 2:00 4:00", r5 , t6);
	t1.addSlot(ts1);
	t2.addSlot(ts2);
	t1.addSlot(ts3);
	t3.addSlot(ts4);
	t3.addSlot(ts5);
	t4.addSlot(ts6);
	t4.addSlot(ts7);
	t5.addSlot(ts8);
	t5.addSlot(ts9);
	t6.addSlot(ts10);
	t6.addSlot(ts11);
	 DropinSlot ds1 = new DropinSlot("2017 4 12 Monday 1:00 3:00", r6);
	 ds1.addTutor(t1);
	 ds1.addTutor(t6);
	 ds1.addCourse(c1);
	 ds1.addCourse(c3);
	 DropinSlot ds2 = new DropinSlot("2017 4 12 Monday 3:00 6:00", r7);
	 ds2.addTutor(t2);
	 ds2.addTutor(t5);
	 ds2.addCourse(c4);
	 ds2.addCourse(c5);
	 d1.addCourse(c1);
	 d1.addCourse(c2);
	 d1.addCourse(c3);
	 d2.addCourse(c4);
	 d2.addCourse(c5);
	 d2.addCourse(c6);
	 d3.addCourse(c7);
	 d3.addCourse(c8);
	 d3.addCourse(c9);
	 master.departments.add(d1);
	 master.departments.add(d2);
	 master.departments.add(d3);
	 master.students.add(s1);
	 master.students.add(s2);
	 master.students.add(s3);
	 master.students.add(s4);
	 master.students.add(s5);
	 master.students.add(s6);
	 master.tutors.add(t1);
	 master.tutors.add(t2);
	 master.tutors.add(t3);
	 master.tutors.add(t4);
	 master.tutors.add(t5);
	 master.tutors.add(t6);
	 master.departments.add(d1);
	 master.departments.add(d2);
	 master.departments.add(d3);
	 master.rooms.add(r1);
	 master.rooms.add(r2);
	 master.rooms.add(r3);
	 master.rooms.add(r4);
	 master.rooms.add(r5);
	 master.rooms.add(r6);
	 master.rooms.add(r7);
	 master.rooms.add(r8);
	 master.rooms.add(r9);
	 Admin.saveData(database);
	 Admin check = new Admin();
	 check = Admin.loadData();
	 
	 
//	 master.schedule.addSlot(ds1);
//	 master.dropinSchedule.addSlot(ds2);
//	 master.dropinSchedule.addSlot(ts1);
//	 master.dropinSchedule.addSlot(ts2);
//	 master.dropinSchedule.addSlot(ts3);
//	 master.dropinSchedule.addSlot(ts4);
//	 master.dropinSchedule.addSlot(ts5);
//	 master.dropinSchedule.addSlot(ts6);
//	 master.dropinSchedule.addSlot(ts7);
//	 master.dropinSchedule.addSlot(ts8);
//	 master.dropinSchedule.addSlot(ts9);
//	 master.dropinSchedule.addSlot(ts10);
//	 master.dropinSchedule.addSlot(ts11);
	 
	
	
	  // Instantiate GUI
			MasterSchedule masterSchedule = null;
			LoginGUI newGUI;
			//InitializeDatabase();
	        newGUI = new LoginGUI(masterSchedule);	
	         
	
	
}
}